# Generated by Django 6.0 on 2026-01-03 19:20

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('family_name', models.CharField(help_text='Ej: Familia Pérez o Juan y Acompañante', max_length=150)),
                ('phone_number', models.CharField(help_text='Formato E.164 para WhatsApp (ej: +521...)', max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente de Envío'), ('SENT', 'Enviado por WhatsApp'), ('DELIVERED', 'Entregado'), ('OPENED', 'Visto por el invitado'), ('COMPLETED', 'Confirmación Completada')], default='PENDING', max_length=20)),
                ('last_sent_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Wedding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(help_text="Identificador para la URL, ej: 'juan-y-maria'", unique=True)),
                ('couple_names', models.CharField(help_text='Ej: Juan y María', max_length=255)),
                ('event_date', models.DateTimeField()),
                ('location_name', models.CharField(blank=True, max_length=255)),
                ('location_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('location_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('theme_config', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('is_child', models.BooleanField(default=False, help_text='¿Requiere menú de niños?')),
                ('attendance', models.CharField(choices=[('PENDING', 'Sin Confirmar'), ('ACCEPTED', 'Asistiré'), ('DECLINED', 'No Asistiré')], default='PENDING', max_length=20)),
                ('dietary_restrictions', models.TextField(blank=True, help_text='Alergias, vegetariano, etc.')),
                ('invitation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guests', to='core.invitation')),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='wedding_photos/%Y/%m/%d/')),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_approved', models.BooleanField(default=True, help_text='Desmarcar para ocultar fotos inapropiadas')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.invitation')),
                ('wedding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='core.wedding')),
            ],
        ),
        migrations.AddField(
            model_name='invitation',
            name='wedding',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='core.wedding'),
        ),
    ]
