# Generated by Django 6.0 on 2026-01-06 06:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_wedding_owner'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='wedding',
            name='claim_code',
            field=models.CharField(blank=True, help_text='Código secreto para reclamar la boda', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='wedding',
            name='owner',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wedding', to=settings.AUTH_USER_MODEL),
        ),
    ]
