# Generated by Django 6.0 on 2026-01-06 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_wedding_claim_code_alter_wedding_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='wedding',
            name='whatsapp_message_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
