# Generated by Django 6.0 on 2026-01-06 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_wedding_whatsapp_message_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wedding',
            name='whatsapp_message_id',
        ),
        migrations.AddField(
            model_name='invitation',
            name='whatsapp_message_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
