# Generated by Django 6.0 on 2026-04-11 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_lead'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pendiente de Envío'), ('SENT', 'Enviado por WhatsApp'), ('DELIVERED', 'Entregado'), ('OPENED', 'Visto por el invitado'), ('COMPLETED', 'Confirmación Completada'), ('DECLINED', 'Rechazada')], default='PENDING', max_length=20),
        ),
    ]
