"""
Django settings for restapi project.

Generated by 'django-admin startproject' using Django 6.0.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import dj_database_url
import os
from dotenv import load_dotenv
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-e$82k1c-gtc$(+^quro^4+stxuu7bofumai&w+ntf=zcj2jg))'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'whitenoise.runserver_nostatic',  # Para servir archivos estáticos en producción
    'core',
    'rest_framework',
    'corsheaders',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'restapi.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'restapi.wsgi.application'

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        #'rest_framework.authentication.SessionAuthentication',
    ),
}

# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': dj_database_url.config(default=os.getenv('DATABASE_URL'))
    # {
    #     'ENGINE': 'django.db.backends.sqlite3',
    #     'NAME': BASE_DIR / 'db.sqlite3',
    # }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATIC_FILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# CORS AND CSRF SETTINGS
CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000", # Tu Next.js local
    "https://*.up.railway.app/api/*", # Comodín para cualquier URL de Railway
    "https://palazzoinvites.com", # Tu producción futura
]

CSRF_TRUSTED_ORIGINS = [
    "http://localhost:3000",
    "https://palazzoinvites.com",
    'https://*.ngrok-free.app', # Comodín para cualquier URL de ngrok
    "https://*.up.railway.app", # Comodín para cualquier URL de Railway
    "https://*.up.railway.app/api/*", # Comodín para cualquier URL de Railway
]

CORS_ALLOW_CREDENTIALS = True
SESSION_COOKIE_SECURE = True


# Celery Configuration Options
CELERY_TASK_ALWAYS_EAGER = True
CELERY_TASK_EAGER_PROPAGATES = True
CELERY_BROKER_URL = 'redis://127.0.0.1:6379/0'

# Credenciales de Meta / Facebook Developers
META_ACCESS_TOKEN = "EAAdHU3VJl14BQSpUMaPmrIr7JvVdlWVaZAVEB4d6aGTUOCj9g1Amr7fixsyLfREoch5wx89TZCWOjyRxp30RfxOpIV5iOoZBzGd4KiaoZBNJX1fE36swc7O3bZAzFcPYVefYIB0eqYfCO9YFa4bi9oIZCWcnxxZCovpxfNIZAH7XAVTPnLC02AzhfisFmjnOZABEJ4plIOpHEQXkWo82Azw2pxHVhkZCejzilja0hYZByCppnrUr7PkCL2fqxQCB2BixclyeZAiESzCaNL9kfcb6dFqcAj7RNmZCugv6YLZASCMgZDZD" # Tu token temporal o permanente
META_PHONE_ID = "963271596861809"      # El ID del número de teléfono (Phone Number ID)
META_API_VERSION = "v22.0"    # O la versión actual