"""
Django settings for restapi project.

Generated by 'django-admin startproject' using Django 6.0.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import dj_database_url
import os
from dotenv import load_dotenv
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-e$82k1c-gtc$(+^quro^4+stxuu7bofumai&w+ntf=zcj2jg))'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['.palazzoinvites.com', '.up.railway.app', 'localhost', 'palazzoinvites.com']

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'whitenoise.runserver_nostatic',  # Para servir archivos estáticos en producción
    'core',
    'rest_framework',
    'corsheaders',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'restapi.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'restapi.wsgi.application'

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        #'rest_framework.authentication.SessionAuthentication',
    ),
}

# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': 
        dj_database_url.config(
            default=os.getenv('DATABASE_URL'),
            conn_max_age=600, # 10 minutos
            ssl_require=True
        )
    # {
    #     'ENGINE': 'django.db.backends.sqlite3',
    #     'NAME': BASE_DIR / 'db.sqlite3',
    # }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATIC_FILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# CORS AND CSRF SETTINGS
CORS_ALLOWED_ORIGINS = [
    "https://app.palazzoinvites.com", 
    "https://api.palazzoinvites.com", # Tu dominio de producción del frontend (si ya existe)
    "https://palazzoinvites.com", # Tu dominio de producción del frontend (si ya existe)
    "http://localhost:3000",
    "http://localhost:5500",
]

CORS_ALLOWED_ORIGIN_REGEXES = [
    r"^https://.*\.up\.railway\.app$",
]

CSRF_TRUSTED_ORIGINS = [
    "http://localhost:3000",      # Tu CRM Next.js
    "http://localhost:5500",      # Variación de local
    "http://127.0.0.1:3000",      # Variación de local
    "https://app.palazzoinvites.com", # Tu dominio de producción del frontend (si ya existe)
    "https://api.palazzoinvites.com", # Tu dominio de producción del frontend (si ya existe)
    "https://palazzoinvites.com", # Tu dominio de producción del frontend (si ya existe)
]

CORS_ALLOW_CREDENTIALS = True
SESSION_COOKIE_SECURE = True

#CSRF_COOKIE_SECURE = not DEBUG 
#SESSION_COOKIE_SECURE = not DEBUG

# CSRF_COOKIE_SAMESITE = 'None' # Esto está bien para cross-site
# SESSION_COOKIE_SAMESITE = 'None'

# SESSION_COOKIE_DOMAIN = ".palazzoinvites.com" # El punto al inicio es clave
# CSRF_COOKIE_DOMAIN = "localhost"


# Celery Configuration Options
CELERY_TASK_ALWAYS_EAGER = True
CELERY_TASK_EAGER_PROPAGATES = True
CELERY_BROKER_URL = os.getenv('REDIS_URL')


# Credenciales de Meta / Facebook Developers
META_ACCESS_TOKEN = os.getenv('META_ACCESS_TOKEN')
META_WEBHOOK_TOKEN = os.getenv('META_WEBHOOK_TOKEN')
META_PHONE_ID = os.getenv('META_PHONE_ID')
META_API_VERSION = "v22.0"